version: 2
jobs:
  build:
    working_directory: ~/working_directory
    docker:
      - image: node:8
        environment:
          NO_WATCH_TESTS: 1
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: yarn --version
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run: yarn install --frozen-lockfile
      - run: yarn run test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
